version: '3.9'
services:
  service1:
    build: ./service1
    container_name: service1
    ports:
      - "3001:8443"
    networks:
      - local

  service2:
    build: ./service2
    container_name: service2
    ports:
      - "3002:8443"
    networks:
      - local

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - local
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  local:
    driver: bridge
